// app/vehicles/[id]/page.tsx

import VehicleDetailPage from "@/app/vehicledetail/page";

// -----------------------------------------------------------------------
// Shared vehicle data — move this to a lib/data/vehicles.ts in production
// -----------------------------------------------------------------------
export const allVehicles = [
  {
    id: 1,
    name: "Lucid Air Touring",
    category: "Cars",
    img: "/Car.jpg",
    price: 120,
    rating: 4.9,
    range: "516 km",
    charge: 95,
    location: "Kathmandu",
    tags: ["Glass Roof", "Autonomous Pilot", "Surround View Cam", "Heated Seats"],
    badge: "PREMIUM",
    seats: 5,
    speed: "250 km/h",
    driveType: "Dual Motor AWD",
    co2Saved: "42.5kg",
    extraImages: [],
    description:
      "The Lucid Air Touring delivers an extraordinary experience that combines heart-pounding performance with an impeccably crafted interior. This specific model features the Glass Canopy roof, providing a panoramic view of the sky, and the Surreal Sound™ Pro system for an immersive auditory journey.",
    host: { name: "Julian V.", trips: 124 },
  },
  {
    id: 2,
    name: "Hyundai IONIQ 5",
    category: "Cars",
    img: "/ioniq.png",
    price: 80,
    rating: 4.7,
    range: "480 km",
    charge: 85,
    location: "Lalitpur",
    tags: ["Fast Charge", "Spacious", "V2L Technology"],
    badge: "POPULAR",
    seats: 5,
    speed: "185 km/h",
    driveType: "Rear Wheel Drive",
    co2Saved: "38kg",
    extraImages: [],
    description:
      "The IONIQ 5 redefines what a modern electric vehicle can be. With ultra-fast 800V charging, a flat floor interior, and vehicle-to-load capability, it's as practical as it is revolutionary.",
    host: { name: "Priya M.", trips: 89 },
  },
  {
    id: 3,
    name: "BMW i4 eDrive40",
    category: "Cars",
    img: "/BMW.png",
    price: 100,
    rating: 4.8,
    range: "590 km",
    charge: 78,
    location: "Bhaktapur",
    tags: ["Premium Audio", "Sport", "M Sport Package"],
    badge: "TOP RATED",
    seats: 4,
    speed: "200 km/h",
    driveType: "Rear Wheel Drive",
    co2Saved: "41kg",
    extraImages: [],
    description:
      "The BMW i4 eDrive40 proves that electric vehicles don't have to sacrifice driving pleasure. With its M Sport suspension and Harman Kardon sound system, it's a gran tourer for the electric age.",
    host: { name: "Rahul S.", trips: 67 },
  },
  {
    id: 4,
    name: "Tesla Model 3",
    category: "Cars",
    img: "/ev_car_white.png",
    price: 90,
    rating: 4.6,
    range: "510 km",
    charge: 92,
    location: "Kathmandu",
    tags: ["Autopilot", "Efficient", "OTA Updates"],
    seats: 5,
    speed: "225 km/h",
    driveType: "Dual Motor AWD",
    co2Saved: "40kg",
    extraImages: [],
    description:
      "The Tesla Model 3 combines minimalist design with maximum performance. Its Autopilot system and over-the-air updates keep it at the cutting edge of automotive technology.",
    host: { name: "Sita K.", trips: 203 },
  },
  {
    id: 5,
    name: "Ather 450X",
    category: "Scooters",
    img: "/ev_scooter.png",
    price: 25,
    rating: 4.5,
    range: "105 km",
    charge: 88,
    location: "Pokhara",
    tags: ["Smart", "Connected", "Fast Charge"],
    badge: "ECO",
    seats: 2,
    speed: "80 km/h",
    driveType: "Single Motor",
    co2Saved: "12kg",
    extraImages: [],
    description: "The Ather 450X is India's smartest electric scooter with a 7-inch touchscreen, turn-by-turn navigation, and a connected app that tracks your rides.",
    host: { name: "Arjun T.", trips: 45 },
  },
  {
    id: 6,
    name: "Ola S1 Pro",
    category: "Scooters",
    img: "/scooters.jpg",
    price: 20,
    rating: 4.3,
    range: "135 km",
    charge: 70,
    location: "Kathmandu",
    tags: ["Budget", "City", "MoveOS"],
    seats: 2,
    speed: "90 km/h",
    driveType: "Single Motor",
    co2Saved: "10kg",
    extraImages: [],
    description: "The Ola S1 Pro with MoveOS delivers a feature-rich ride at an accessible price. Hyper mode unlocks its full 90 km/h potential for those who like a little thrill.",
    host: { name: "Meera J.", trips: 31 },
  },
  {
    id: 7,
    name: "Revolt RV400",
    category: "Bikes",
    img: "/ev_motorcycle.png",
    price: 45,
    rating: 4.4,
    range: "150 km",
    charge: 60,
    location: "Lalitpur",
    tags: ["Sporty", "AI Sound", "App-enabled"],
    badge: "NEW",
    seats: 2,
    speed: "85 km/h",
    driveType: "Single Motor",
    co2Saved: "18kg",
    extraImages: [],
    description: "The Revolt RV400 is India's first AI-enabled motorcycle. Switch between four riding modes and even customise your engine sound via the app.",
    host: { name: "Bikash R.", trips: 19 },
  },
  {
    id: 8,
    name: "Ultraviolette F77",
    category: "Bikes",
    img: "/bikes.jpg",
    price: 55,
    rating: 4.6,
    range: "200 km",
    charge: 75,
    location: "Bhaktapur",
    tags: ["Performance", "Track", "Aerospace-grade"],
    seats: 2,
    speed: "155 km/h",
    driveType: "Single Motor",
    co2Saved: "22kg",
    extraImages: [],
    description: "Built with aerospace-grade materials, the F77 is the most powerful electric motorcycle available for rent. Cornering ABS and traction control keep you safe at track speeds.",
    host: { name: "Dev P.", trips: 27 },
  },
  {
    id: 9,
    name: "Trek Domane+ SLR",
    category: "Cycles",
    img: "/ev_bicycle.png",
    price: 15,
    rating: 4.2,
    range: "90 km",
    charge: 100,
    location: "Pokhara",
    tags: ["Fitness", "Trail", "Lightweight"],
    seats: 1,
    speed: "45 km/h",
    driveType: "Pedal Assist",
    co2Saved: "5kg",
    extraImages: [],
    description: "The Trek Domane+ SLR blends road endurance geometry with a whisper-quiet motor for assisted climbing. Perfect for Pokhara's scenic valley roads.",
    host: { name: "Nima S.", trips: 58 },
  },
  {
    id: 10,
    name: "Giant Trance X E+",
    category: "Cycles",
    img: "/cycle.jpg",
    price: 12,
    rating: 4.1,
    range: "75 km",
    charge: 95,
    location: "Kathmandu",
    tags: ["Mountain", "Assist", "Trail"],
    seats: 1,
    speed: "40 km/h",
    driveType: "Pedal Assist",
    co2Saved: "4kg",
    extraImages: [],
    description: "Tackle Kathmandu's mountain trails with ease. The Giant Trance X E+ offers 150mm of travel and a Yamaha SyncDrive Sport motor for effortless climbs.",
    host: { name: "Pema D.", trips: 40 },
  },
  {
    id: 11,
    name: "Nissan Leaf",
    category: "Cars",
    img: "/leaf.png",
    price: 70,
    rating: 4.5,
    range: "364 km",
    charge: 82,
    location: "Pokhara",
    tags: ["Compact", "Family", "ProPilot"],
    seats: 5,
    speed: "157 km/h",
    driveType: "Front Wheel Drive",
    co2Saved: "30kg",
    extraImages: [],
    description: "The Nissan Leaf e+ is the world's best-selling electric car for a reason. Reliable, comfortable, and packed with safety tech including ProPilot Assist.",
    host: { name: "Anita G.", trips: 112 },
  },
  {
    id: 12,
    name: "TVS iQube",
    category: "Scooters",
    img: "/ev_scooter.png",
    price: 18,
    rating: 4.0,
    range: "100 km",
    charge: 65,
    location: "Lalitpur",
    tags: ["Affordable", "Commute", "SmartXonnect"],
    seats: 2,
    speed: "78 km/h",
    driveType: "Single Motor",
    co2Saved: "9kg",
    extraImages: [],
    description: "The TVS iQube is designed for the daily urban commute. SmartXonnect Bluetooth integration lets you answer calls, check navigation, and monitor battery — all from the dash.",
    host: { name: "Rajan B.", trips: 22 },
  },
];

// -----------------------------------------------------------------------
// App Router page — Next.js 15+ requires awaiting params
// -----------------------------------------------------------------------
interface Props {
  params: Promise<{ id: string }>;
}

export default async function Page({ params }: Props) {
  const { id } = await params;
  const vehicle = allVehicles.find(v => v.id === Number(id));

  if (!vehicle) {
    return (
      <div className="min-h-screen flex items-center justify-center text-gray-500">
        Vehicle not found.
      </div>
    );
  }

  return <VehicleDetailPage vehicle={vehicle} />;
}

// Optional: pre-generate static pages at build time
export function generateStaticParams() {
  return allVehicles.map(v => ({ id: String(v.id) }));
}